// const cardData = [
//     { question: "教室", answer: ["classroom"] },
//     { question: "老师", answer: ["Teacher"] },
//     { question: "我们", answer: ["We"] },
//     { question: "唱歌", answer: ["Sing"] },
//     { question: "跳舞", answer: ["Dance"] },
//     { question: "教学", answer: ["Teach"] },
//     { question: "学习", answer: ["learn", "study"] },
//     { question: "中文", answer: ["chinese","mandarin"] },
//     { question: "学校", answer: ["School"] },
//     { question: "春天", answer: ["Spring"]},
//     { question: "秋天", answer: ["Fall", "autumn"] },
//     { question: "夏天", answer: ["Summer"] },
//     { question: "冬天", answer: ["Winter"] },
//     { question: "衣服", answer: ["Clothes"] },
//     { question: "铅笔", answer: ["Pencil"] },
//     { question: "橡皮", answer: ["eraser"] },
//     { question: "文具盒", answer: ["pencil case","pencil box",'pencilbox','pencilcase']},
//     { question: "画画儿", answer: ["painting",'drawing','draw'] },
//     { question: "裤子", answer: ["pants"] },
//     { question: "裙子", answer: ["skirt"] },
//     { question: "袜子", answer: ["socks",'sock'] },
//     { question: "名字", answer: ["name"] },
//     { question: "蔬菜", answer: ["vegetavles"] },
//     { question: "牛肉", answer: ["beef"] },
//     { question: "猪肉", answer: ["pork"] },
//     { question: "午餐", answer: ["lunch"] },
//     { question: "早餐", answer: ["breakfast"] },
//     { question: "晚餐", answer: ["dinner"] },
//     { question: "鸡蛋", answer: ["egg"] },
//     { question: "牛奶", answer: ["milk"] },
//     { question: "麦片", answer: ["cereal"] },
//     { question: "面包", answer: ["bread"] },
//     { question: "苹果", answer: ["apple"] },
//     { question: "水", answer: ["water"] },
//     { question: "咖啡", answer: ["coffee"] },
//     { question: "茶", answer: ["tea"] },
//     { question: "鸡蛋", answer: ["egg"] },
//     { question: "香蕉", answer: ["banana"] },
//     { question: "鱼", answer: ["fish"] },
//     { question: "肉", answer: ["meat"] },
//     { question: "书", answer: ["book"] },
//     { question: "笔", answer: ["pen"] },
//     { question: "桌子", answer: ["table"] },
//     { question: "椅子", answer: ["chair"] },
//     { question: "手机", answer: ["phone"] },
//     { question: "电脑", answer: ["computer"] },
//     { question: "汽车", answer: ["car"] },
//     { question: "自行车", answer: ["bicycle"] },
//     { question: "飞机", answer: ["airplane"] },
//     { question: "火车", answer: ["train"] },
//     { question: "猫", answer: ["cat"] },
//     { question: "狗", answer: ["dog"] },
//     { question: "鸟", answer: ["bird"] },
//     { question: "雨", answer: ["rain"] },
//     { question: "太阳", answer: ["sun"] },
//     { question: "月亮", answer: ["moon"] },
//     { question: "星星", answer: ["star"] },
//     { question: "山", answer: ["mountain"] },
//     { question: "河", answer: ["river"] },
//     { question: "海", answer: ["sea"] },
//     { question: "城市", answer: ["city"] },
//     { question: "村庄", answer: ["village"] },
//     { question: "书店", answer: ["bookstore"] },
//     { question: "图书馆", answer: ["library"] },
//     { question: "超市", answer: ["supermarket"] },
//     { question: "医院", answer: ["hospital"] },
//     { question: "火车站", answer: ["train station"] },
//     { question: "机场", answer: ["airport"] },
//     { question: "公园", answer: ["park"] },
//     { question: "家", answer: ["home",'house'] },

//   ];

  const cardData = [
    {
      unit: "轻松学中文1 第一单元",
      words: [
        { question: "教室", answer: ["classroom"] },
        { question: "老师", answer: ["teacher"] },
        { question: "我们", answer: ["we"] },
        { question: "唱歌", answer: ["sing"] },
        { question: "跳舞", answer: ["dance"] },
        { question: "教学", answer: ["teach"] },
        { question: "学习", answer: ["learn", "study"] },
        { question: "中文", answer: ["chinese", "mandarin"] },
        { question: "学校", answer: ["school"] },
        { question: "铅笔", answer: ["pencil"] },
        { question: "橡皮", answer: ["eraser"] },
        { question: "文具盒", answer: ["pencil case", "pencil box"] },
      ],
    },
    {
      unit: "轻松学中文1 第二单元",
      words: [
        { question: "春天", answer: ["spring"] },
        { question: "夏天", answer: ["summer"] },
        { question: "秋天", answer: ["fall", "autumn"] },
        { question: "冬天", answer: ["winter"] },
        { question: "衣服", answer: ["clothes"] },
        { question: "裤子", answer: ["pants"] },
        { question: "裙子", answer: ["skirt"] },
        { question: "袜子", answer: ["socks"] },
        { question: "鞋子", answer: ["shoes"] },
        { question: "帽子", answer: ["hat"] },
        { question: "围巾", answer: ["scarf"] },
        { question: "手套", answer: ["gloves"] },
      ],
    },
    {
      unit: "轻松学中文1 第三单元",
      words: [
        { question: "早餐", answer: ["breakfast"] },
        { question: "午餐", answer: ["lunch"] },
        { question: "晚餐", answer: ["dinner"] },
        { question: "鸡蛋", answer: ["egg"] },
        { question: "牛奶", answer: ["milk"] },
        { question: "面包", answer: ["bread"] },
        { question: "苹果", answer: ["apple"] },
        { question: "香蕉", answer: ["banana"] },
        { question: "鱼", answer: ["fish"] },
        { question: "肉", answer: ["meat"] },
        { question: "蔬菜", answer: ["vegetables"] },
        { question: "水", answer: ["water"] },
        { question: "茶", answer: ["tea"] },
        { question: "咖啡", answer: ["coffee"] },
      ],
    },
    {
      unit: "轻松学中文1 第四单元",
      words: [
        { question: "家", answer: ["home", "house"] },
        { question: "桌子", answer: ["table"] },
        { question: "椅子", answer: ["chair"] },
        { question: "书", answer: ["book"] },
        { question: "电脑", answer: ["computer"] },
        { question: "手机", answer: ["phone"] },
        { question: "灯", answer: ["lamp", "light"] },
        { question: "床", answer: ["bed"] },
        { question: "沙发", answer: ["sofa", "couch"] },
        { question: "电视", answer: ["television", "TV"] },
        { question: "门", answer: ["door"] },
        { question: "窗户", answer: ["window"] },
      ],
    },
    {
      unit: "轻松学中文2 第一单元",
      words: [
        { question: "超市", answer: ["supermarket"] },
        { question: "医院", answer: ["hospital"] },
        { question: "书店", answer: ["bookstore"] },
        { question: "图书馆", answer: ["library"] },
        { question: "火车站", answer: ["train station"] },
        { question: "机场", answer: ["airport"] },
        { question: "公园", answer: ["park"] },
        { question: "邮局", answer: ["post office"] },
        { question: "银行", answer: ["bank"] },
        { question: "饭店", answer: ["restaurant"] },
      ],
    },
    {
      unit: "轻松学中文2 第二单元",
      words: [
        { question: "猫", answer: ["cat"] },
        { question: "狗", answer: ["dog"] },
        { question: "鸟", answer: ["bird"] },
        { question: "鱼", answer: ["fish"] },
        { question: "兔子", answer: ["rabbit"] },
        { question: "马", answer: ["horse"] },
        { question: "牛", answer: ["cow"] },
        { question: "猪", answer: ["pig"] },
        { question: "羊", answer: ["sheep"] },
        { question: "鸡", answer: ["chicken"] },
      ],
    },
    {
      unit: "轻松学中文2 第三单元",
      words: [
        { question: "太阳", answer: ["sun"] },
        { question: "月亮", answer: ["moon"] },
        { question: "星星", answer: ["star"] },
        { question: "山", answer: ["mountain"] },
        { question: "河", answer: ["river"] },
        { question: "海", answer: ["sea"] },
        { question: "湖", answer: ["lake"] },
        { question: "草地", answer: ["grassland"] },
        { question: "森林", answer: ["forest"] },
        { question: "天空", answer: ["sky"] },
      ],
    },
    {
      unit: "轻松学中文2 第四单元",
      words: [
        { question: "汽车", answer: ["car"] },
        { question: "自行车", answer: ["bicycle"] },
        { question: "火车", answer: ["train"] },
        { question: "飞机", answer: ["airplane"] },
        { question: "轮船", answer: ["ship"] },
        { question: "公交车", answer: ["bus"] },
        { question: "出租车", answer: ["taxi"] },
        { question: "摩托车", answer: ["motorcycle"] },
        { question: "地铁", answer: ["subway"] },
        { question: "船", answer: ["boat"] },
      ],
    },
  ];
  

export default cardData;