const cardData = [
    { question: "教室", answer: ["classroom"] },
    { question: "老师", answer: ["Teacher"] },
    { question: "我们", answer: ["We"] },
    { question: "唱歌", answer: ["Sing"] },
    { question: "跳舞", answer: ["Dance"] },
    { question: "教学", answer: ["Teach"] },
    { question: "学习", answer: ["learn", "study"] },
    { question: "中文", answer: ["chinese","mandarin"] },
    { question: "学校", answer: ["School"] },
    { question: "春天", answer: ["Spring"]},
    { question: "秋天", answer: ["Fall", "autumn"] },
    { question: "夏天", answer: ["Summer"] },
    { question: "冬天", answer: ["Winter"] },
    { question: "衣服", answer: ["Clothes"] },
    { question: "铅笔", answer: ["Pencil"] },
    { question: "橡皮", answer: ["eraser"] },
    { question: "文具盒", answer: ["pencil case","pencil box",'pencilbox','pencilcase']},
    { question: "画画儿", answer: ["painting",'drawing','draw'] },
    { question: "裤子", answer: ["pants"] },
    { question: "裙子", answer: ["skirt"] },
    { question: "袜子", answer: ["socks",'sock'] },
    { question: "名字", answer: ["name"] },
    { question: "蔬菜", answer: ["vegetavles"] },
    { question: "牛肉", answer: ["beef"] },
    { question: "猪肉", answer: ["pork"] },
    { question: "午餐", answer: ["lunch"] },
    { question: "早餐", answer: ["breakfast"] },
    { question: "晚餐", answer: ["dinner"] },
    { question: "鸡蛋", answer: ["egg"] },
    { question: "牛奶", answer: ["milk"] },
    { question: "麦片", answer: ["cereal"] },
    { question: "面包", answer: ["bread"] },
    { question: "苹果", answer: ["apple"] },
    { question: "水", answer: ["water"] },
    { question: "咖啡", answer: ["coffee"] },
    { question: "茶", answer: ["tea"] },
    { question: "鸡蛋", answer: ["egg"] },
    { question: "香蕉", answer: ["banana"] },
    { question: "鱼", answer: ["fish"] },
    { question: "肉", answer: ["meat"] },
    { question: "书", answer: ["book"] },
    { question: "笔", answer: ["pen"] },
    { question: "桌子", answer: ["table"] },
    { question: "椅子", answer: ["chair"] },
    { question: "手机", answer: ["phone"] },
    { question: "电脑", answer: ["computer"] },
    { question: "汽车", answer: ["car"] },
    { question: "自行车", answer: ["bicycle"] },
    { question: "飞机", answer: ["airplane"] },
    { question: "火车", answer: ["train"] },
    { question: "猫", answer: ["cat"] },
    { question: "狗", answer: ["dog"] },
    { question: "鸟", answer: ["bird"] },
    { question: "雨", answer: ["rain"] },
    { question: "太阳", answer: ["sun"] },
    { question: "月亮", answer: ["moon"] },
    { question: "星星", answer: ["star"] },
    { question: "山", answer: ["mountain"] },
    { question: "河", answer: ["river"] },
    { question: "海", answer: ["sea"] },
    { question: "城市", answer: ["city"] },
    { question: "村庄", answer: ["village"] },
    { question: "书店", answer: ["bookstore"] },
    { question: "图书馆", answer: ["library"] },
    { question: "超市", answer: ["supermarket"] },
    { question: "医院", answer: ["hospital"] },
    { question: "火车站", answer: ["train station"] },
    { question: "机场", answer: ["airport"] },
    { question: "公园", answer: ["park"] },
    { question: "家", answer: ["home",'house'] },

  ];

export default cardData;